server:
  port: 9090
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: test-application
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:test_db
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console