server:
  port: 9090
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: test-application
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    password: admin
    username: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  h2:
    console:
      enabled: false